Add item requests
JackobTheLion/java-shareit pull request #4
Opened 2023-07-11 11:35 UTC by JackobTheLion

2023-07-12 08:18 UTC, YazykovMikhail requested changes

2023-07-12 08:18 UTC, YazykovMikhail commented on src/main/resources/schema.sql
> +create table if not exists requests
лучше конечно назвать
item_requests
ведь реквестом может быть много

2023-07-12 08:18 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/request/service/RequestService.java
> +        PageRequest page = PageRequest.of(from > 0 ? from / size : 0, size);
Вот так будет получше 
		final PageRequest pageRequest = FromSizeRequest.of(from, size, Sort.by(DESC, "created"));
и сразу с сортировкой

2023-07-12 08:18 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/request/service/RequestService.java
> +        PageRequest page = PageRequest.of(from > 0 ? from / size : 0, size);
Вот так будет получше
final PageRequest pageRequest = FromSizeRequest.of(from, size, Sort.by(DESC, "created"));
и сразу с сортировкой

2023-07-12 08:18 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/request/service/RequestService.java
> +        request.setCreated(Timestamp.valueOf(LocalDateTime.now()));
Что ьбы так неделать, в поле dto сделай:
	private LocalDateTime created = LocalDateTime.now();

2023-07-12 08:18 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/request/model/Request.java
> +public class Request {
Верни название ItemRequest

2023-07-12 08:18 UTC, YazykovMikhail commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +public class BookingRepositoryTest {
Как могут выглядеть тесты для репозитория:

```
@DataJpaTest
class BookingRepositoryITest {

    @Autowired
    private BookingRepository bookingRepository;

    @Autowired
    private UserRepository userRepository;
    @Autowired
    private ItemRepository itemRepository;

    private Item item;

    private User booker;

    @BeforeEach
    void setUp() {
        this.item = createItem("Pencil", "Basic drawing tool", false, createUser("Mike Turtle", "mikelangelo@tmnt.com"));
        this.booker = createUser("Mr. Smith", "find.neo@matrix.com");
    }

    private Item createItem(String name, String description, boolean available, User owner) {
        var item = new Item();
        item.setAvailable(available);
        item.setName(name);
        item.setDescription(description);
        item.setOwner(owner);
        return itemRepository.save(item);
    }

    private User createUser(String name, String email) {
        var owner = new User();
        owner.setName(name);
        owner.setEmail(email);
        return userRepository.save(owner);
    }

    private Booking createBooking(BookingStatus status, Item item, User booker, LocalDateTime start, LocalDateTime end) {
        var booking = new Booking();
        booking.setStatus(status);
        booking.setItem(item);
        booking.setBooker(booker);
        booking.setStart(start);
        booking.setEnd(end);
        return bookingRepository.save(booking);
    }

    @Test
    void testFindApprovedItems() {
        var booking = createBooking(BookingStatus.APPROVED, item, booker, LocalDateTime.now(), LocalDateTime.now());
        var result = bookingRepository.findApprovedForItems(Collections.singleton(item), Sort.unsorted());
        Assertions.assertNotNull(result);
        Assertions.assertEquals(1, result.size());
        Assertions.assertEquals(booking.getId(), result.get(0).getId());
        Assertions.assertEquals(booking.getStatus(), result.get(0).getStatus());
    }

    @Test
    void testFindPendingItems() {
        var booking = createBooking(BookingStatus.WAITING, item, booker, LocalDateTime.now(), LocalDateTime.now());
        var result = bookingRepository.findPending(booker.getId(), Pageable.unpaged());
        Assertions.assertNotNull(result);
        Assertions.assertEquals(1, result.getTotalElements());
        Assertions.assertEquals(booking.getId(), result.getContent().get(0).getId());
        Assertions.assertEquals(booking.getStatus(), result.getContent().get(0).getStatus());
    }

    @Test
    void testFindOwnerPendingItems() {
        var booking = createBooking(BookingStatus.WAITING, item, booker, LocalDateTime.now(), LocalDateTime.now());
        var result = bookingRepository.findOwnerPending(item.getOwner().getId(), Pageable.unpaged());
        Assertions.assertNotNull(result);
        Assertions.assertEquals(1, result.getTotalElements());
        Assertions.assertEquals(booking.getId(), result.getContent().get(0).getId());
        Assertions.assertEquals(booking.getStatus(), result.getContent().get(0).getStatus());
    }

    @Test
    void testFindCurrentForDate() {
        var start = LocalDateTime.now().plusDays(-1);
        var end = LocalDateTime.now().plusDays(1);
        var booking = createBooking(BookingStatus.WAITING, item, booker, start, end);
        var result = bookingRepository.findCurrentForDate(booker.getId(), LocalDateTime.now(), Pageable.unpaged());
        Assertions.assertNotNull(result);
        Assertions.assertEquals(1, result.getTotalElements());
        Assertions.assertEquals(booking.getId(), result.getContent().get(0).getId());
        Assertions.assertEquals(booking.getStatus(), result.getContent().get(0).getStatus());
    }

    @Test
    void testFindOwnerForDate() {
        var start = LocalDateTime.now().plusDays(-1);
        var end = LocalDateTime.now().plusDays(1);
        var booking = createBooking(BookingStatus.WAITING, item, booker, start, end);
        var result = bookingRepository.findOwnerCurrentForDate(item.getOwner().getId(), LocalDateTime.now(), Pageable.unpaged());
        Assertions.assertNotNull(result);
        Assertions.assertEquals(1, result.getTotalElements());
        Assertions.assertEquals(booking.getId(), result.getContent().get(0).getId());
        Assertions.assertEquals(booking.getStatus(), result.getContent().get(0).getStatus());
    }

    @Test
    void testFindCanceledItems() {
        var booking = createBooking(BookingStatus.CANCELED, item, booker, LocalDateTime.now(), LocalDateTime.now());
        var result = bookingRepository.findCanceled(booker.getId(), Pageable.unpaged());
        Assertions.assertNotNull(result);
        Assertions.assertEquals(1, result.getTotalElements());
        Assertions.assertEquals(booking.getId(), result.getContent().get(0).getId());
        Assertions.assertEquals(booking.getStatus(), result.getContent().get(0).getStatus());
    }

    @Test
    void testFindRejectedItems() {
        var booking = createBooking(BookingStatus.REJECTED, item, booker, LocalDateTime.now(), LocalDateTime.now());
        var result = bookingRepository.findCanceled(booker.getId(), Pageable.unpaged());
        Assertions.assertNotNull(result);
        Assertions.assertEquals(1, result.getTotalElements());
        Assertions.assertEquals(booking.getId(), result.getContent().get(0).getId());
        Assertions.assertEquals(booking.getStatus(), result.getContent().get(0).getStatus());
    }

    @Test
    void testFindOwnerCanceledItems() {
        var booking = createBooking(BookingStatus.CANCELED, item, booker, LocalDateTime.now(), LocalDateTime.now());
        var result = bookingRepository.findOwnerCanceled(item.getOwner().getId(), Pageable.unpaged());
        Assertions.assertNotNull(result);
        Assertions.assertEquals(1, result.getTotalElements());
        Assertions.assertEquals(booking.getId(), result.getContent().get(0).getId());
        Assertions.assertEquals(booking.getStatus(), result.getContent().get(0).getStatus());
    }

    @Test
    void testFindOwnerRejectedItems() {
        var booking = createBooking(BookingStatus.REJECTED, item, booker, LocalDateTime.now(), LocalDateTime.now());
        var result = bookingRepository.findOwnerCanceled(item.getOwner().getId(), Pageable.unpaged());
        Assertions.assertNotNull(result);
        Assertions.assertEquals(1, result.getTotalElements());
        Assertions.assertEquals(booking.getId(), result.getContent().get(0).getId());
        Assertions.assertEquals(booking.getStatus(), result.getContent().get(0).getStatus());
    }

    @Test
    void testIsAvailableForBooking() {
        var start = LocalDateTime.now().plusDays(-2);
        var end = LocalDateTime.now().plusDays(2);
        var booking = createBooking(BookingStatus.APPROVED, item, booker, start, end);
        Assertions.assertTrue(bookingRepository.isAvailableForBooking(item.getId(), LocalDateTime.now().plusDays(-1), LocalDateTime.now().plusDays(1)));
        Assertions.assertFalse(bookingRepository.isAvailableForBooking(item.getId(), LocalDateTime.now().plusDays(-3), LocalDateTime.now().plusDays(3)));
    }

    @AfterEach
    void tearDown() {
        bookingRepository.deleteAll();
        itemRepository.deleteAll();
        userRepository.deleteAll();
    }

```

2023-07-12 08:18 UTC, YazykovMikhail commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    private int from = 0;
Очень много лишних переменных, это не поля класса, они не характеризуют свойство класса. 

```
class BookingServiceImplTest {

	private BookingServiceImpl bookingService;

	private BookingRepository bookingRepository;
	private UserRepository userRepository;
	private ItemRepository itemRepository;

	private User user;

	@BeforeEach
	void setUp() {
		bookingRepository = mock(BookingRepository.class);
		when(bookingRepository.save(any())).thenAnswer(invocation -> invocation.getArgument(0));
		userRepository = mock(UserRepository.class);
		itemRepository = mock(ItemRepository.class);
		bookingService = new BookingServiceImpl(bookingRepository, userRepository, itemRepository);
		user = new User();
		user.setId(1L);
		user.setName("John");
		user.setEmail("test@google.com");
	}

	@Test
	void getBookingsAll() {
		when(userRepository.findById(user.getId())).thenReturn(Optional.of(user));
		when(bookingRepository.findByBooker_Id(any(), any())).thenReturn(Page.empty());
		var result = bookingService.getBookings(1L, BookingState.ALL, Pageable.unpaged());
		Assertions.assertNotNull(result);
		Assertions.assertTrue(result.isEmpty());
		verify(bookingRepository, times(1)).findByBooker_Id(any(), any());
	}

	@Test
	void getBookingsPast() {
		when(userRepository.findById(user.getId())).thenReturn(Optional.of(user));
		when(bookingRepository.findByBooker_IdAndEndIsBefore(any(), any(), any())).thenReturn(Page.empty());
		var result = bookingService.getBookings(1L, BookingState.PAST, Pageable.unpaged());
		Assertions.assertNotNull(result);
		Assertions.assertTrue(result.isEmpty());
		verify(bookingRepository, times(1)).findByBooker_IdAndEndIsBefore(any(), any(), any());
	}

	@Test
	void getBookingsFuture() {
		when(userRepository.findById(user.getId())).thenReturn(Optional.of(user));
		when(bookingRepository.findByBooker_IdAndStartIsAfter(any(), any(), any())).thenReturn(Page.empty());
		var result = bookingService.getBookings(1L, BookingState.FUTURE, Pageable.unpaged());
		Assertions.assertNotNull(result);
		Assertions.assertTrue(result.isEmpty());
		verify(bookingRepository, times(1)).findByBooker_IdAndStartIsAfter(any(), any(), any());
	}

	@Test
	void getBookingsCurrent() {
		when(userRepository.findById(user.getId())).thenReturn(Optional.of(user));
		when(bookingRepository.findCurrentForDate(any(), any(), any())).thenReturn(Page.empty());
		var result = bookingService.getBookings(1L, BookingState.CURRENT, Pageable.unpaged());
		Assertions.assertNotNull(result);
		Assertions.assertTrue(result.isEmpty());
		verify(bookingRepository, times(1)).findCurrentForDate(any(), any(), any());
	}

	@Test
	void getBookingsWaiting() {
		when(userRepository.findById(user.getId())).thenReturn(Optional.of(user));
		when(bookingRepository.findPending(any(), any())).thenReturn(Page.empty());
		var result = bookingService.getBookings(1L, BookingState.WAITING, Pageable.unpaged());
		Assertions.assertNotNull(result);
		Assertions.assertTrue(result.isEmpty());
		verify(bookingRepository, times(1)).findPending(any(), any());
	}

	@Test
	void getBookingsRejected() {
		when(userRepository.findById(user.getId())).thenReturn(Optional.of(user));
		when(bookingRepository.findCanceled(any(), any())).thenReturn(Page.empty());
		var result = bookingService.getBookings(1L, BookingState.REJECTED, Pageable.unpaged());
		Assertions.assertNotNull(result);
		Assertions.assertTrue(result.isEmpty());
		verify(bookingRepository, times(1)).findCanceled(any(), any());
	}

	@Test
	void getOwnerBookingsAll() {
		when(userRepository.findById(user.getId())).thenReturn(Optional.of(user));
		when(bookingRepository.findByItem_Owner_Id(any(), any())).thenReturn(Page.empty());
		var result = bookingService.getOwnerBookings(1L, BookingState.ALL, Pageable.unpaged());
		Assertions.assertNotNull(result);
		Assertions.assertTrue(result.isEmpty());
		verify(bookingRepository, times(1)).findByItem_Owner_Id(any(), any());
	}

	@Test
	void getOwnerBookingsPast() {
		when(userRepository.findById(user.getId())).thenReturn(Optional.of(user));
		when(bookingRepository.findByItem_Owner_IdAndEndIsBefore(any(), any(), any())).thenReturn(Page.empty());
		var result = bookingService.getOwnerBookings(1L, BookingState.PAST, Pageable.unpaged());
		Assertions.assertNotNull(result);
		Assertions.assertTrue(result.isEmpty());
		verify(bookingRepository, times(1)).findByItem_Owner_IdAndEndIsBefore(any(), any(), any());
	}

	@Test
	void getOwnerBookingsFuture() {
		when(userRepository.findById(user.getId())).thenReturn(Optional.of(user));
		when(bookingRepository.findByItem_Owner_IdAndStartIsAfter(any(), any(), any())).thenReturn(Page.empty());
		var result = bookingService.getOwnerBookings(1L, BookingState.FUTURE, Pageable.unpaged());
		Assertions.assertNotNull(result);
		Assertions.assertTrue(result.isEmpty());
		verify(bookingRepository, times(1)).findByItem_Owner_IdAndStartIsAfter(any(), any(), any());
	}

	@Test
	void getOwnerBookingsCurrent() {
		when(userRepository.findById(user.getId())).thenReturn(Optional.of(user));
		when(bookingRepository.findOwnerCurrentForDate(any(), any(), any())).thenReturn(Page.empty());
		var result = bookingService.getOwnerBookings(1L, BookingState.CURRENT, Pageable.unpaged());
		Assertions.assertNotNull(result);
		Assertions.assertTrue(result.isEmpty());
		verify(bookingRepository, times(1)).findOwnerCurrentForDate(any(), any(), any());
	}

	@Test
	void getOwnerBookingsWaiting() {
		when(userRepository.findById(user.getId())).thenReturn(Optional.of(user));
		when(bookingRepository.findOwnerPending(any(), any())).thenReturn(Page.empty());
		var result = bookingService.getOwnerBookings(1L, BookingState.WAITING, Pageable.unpaged());
		Assertions.assertNotNull(result);
		Assertions.assertTrue(result.isEmpty());
		verify(bookingRepository, times(1)).findOwnerPending(any(), any());
	}

	@Test
	void getOwnerBookingsRejected() {
		when(userRepository.findById(user.getId())).thenReturn(Optional.of(user));
		when(bookingRepository.findOwnerCanceled(any(), any())).thenReturn(Page.empty());
		var result = bookingService.getOwnerBookings(1L, BookingState.REJECTED, Pageable.unpaged());
		Assertions.assertNotNull(result);
		Assertions.assertTrue(result.isEmpty());
		verify(bookingRepository, times(1)).findOwnerCanceled(any(), any());
	}

	@Test
	void bookItem() {
		var userId = 1L;
		var user = new User();
		user.setId(2L);
		when(userRepository.findById(userId)).thenReturn(Optional.of(user));
		var requestDto = new BookItemRequestDto(1L, LocalDateTime.now(), LocalDateTime.now());
		Item item = new Item();
		item.setId(3L);
		item.setOwner(user);
		item.setAvailable(true);
		when(itemRepository.findById(requestDto.getItemId())).thenReturn(Optional.of(item));
		var result = bookingService.bookItem(userId, requestDto);
		Assertions.assertNotNull(result);
	}

	@Test
	void getBooking() {
		var bookingId = 2L;
        when(userRepository.findById(user.getId())).thenReturn(Optional.of(user));
		when(bookingRepository.findById(bookingId)).thenReturn(Optional.empty());
		Assertions.assertThrows(NotFoundException.class, () -> bookingService.getBooking(user.getId(), bookingId));
	}

	@Test
	void setBookingApproveStateApproved() {
		var bookingId = 2L;
		var approved = true;
		Item item = new Item();
		item.setId(3L);
		item.setOwner(user);
		item.setAvailable(true);
		var booking = new Booking();
		booking.setId(3L);
		booking.setStatus(BookingStatus.WAITING);
		booking.setStart(LocalDateTime.now().plusDays(1));
		booking.setBooker(user);
		booking.setItem(item);
        when(userRepository.findById(user.getId())).thenReturn(Optional.of(user));
		when(bookingRepository.findByIdAndItem_Owner_Id(bookingId, user.getId())).thenReturn(Optional.of(booking));
		var result = bookingService.setBookingApproveState(user.getId(), bookingId, approved);
		Assertions.assertNotNull(result);
		Assertions.assertEquals(BookingStatus.APPROVED, result.getStatus());
	}

	@Test
	void setBookingApproveStateRejected() {
		var bookingId = 2L;
		var appro [...]

2023-07-12 08:18 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/request/dto/RequestDto.java
> +public class RequestDto {
У тебя одно dto  ина запрос и на ответ?
это не верно, нужно иметь два(как минимум, а то и на каждый запрос свой dto для запрос и для ответа)

ItemRequestDto
ItemResponseDto
сделай

поправь это везде. dto для запроса и ответа должны быть разные

2023-07-13 12:35 UTC, JackobTheLion commented on src/main/java/ru/practicum/shareit/request/service/RequestService.java
> +        PageRequest page = PageRequest.of(from > 0 ? from / size : 0, size);
По условиям ТЗ мы указываем индекс начального элемента и страницу, а не просто размер и номер страницы.

2023-07-13 12:35 UTC, JackobTheLion commented on src/main/java/ru/practicum/shareit/request/service/RequestService.java
> +        PageRequest page = PageRequest.of(from > 0 ? from / size : 0, size);
По условиям ТЗ мы указываем индекс начального элемента и страницу, а не просто размер и номер страницы.

2023-07-13 13:11 UTC, merged